{{- if .Values.components.externalSecretsStore.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.components.externalSecretsStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.components.externalSecretsStore.vault.server }}
      path: {{ .Values.components.externalSecretsStore.vault.path }}
      version: {{ .Values.components.externalSecretsStore.vault.version }}
      auth:
        kubernetes:
          mountPath: {{ .Values.components.externalSecretsStore.vault.auth.kubernetes.mountPath }}
          role: {{ .Values.components.externalSecretsStore.vault.auth.kubernetes.role }}
          serviceAccountRef:
            name: {{ .Values.components.externalSecretsStore.vault.auth.kubernetes.serviceAccountRef.name }}
            namespace: {{ .Values.components.externalSecretsStore.vault.auth.kubernetes.serviceAccountRef.namespace }}
{{- end }}
