{{- if .Values.components.externalDns.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.components.externalDns.secret.name }}
  namespace: {{ .Values.namespaces.platform }}
spec:
  refreshInterval: {{ .Values.components.externalDns.secret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.components.externalDns.secret.secretStoreRef.kind }}
    name: {{ .Values.components.externalDns.secret.secretStoreRef.name }}
  target:
    name: {{ .Values.components.externalDns.secret.target.name }}
    creationPolicy: {{ .Values.components.externalDns.secret.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.components.externalDns.secret.data.secretKey }}
      remoteRef:
        key: {{ .Values.components.externalDns.secret.data.remoteRef.key }}
        property: {{ .Values.components.externalDns.secret.data.remoteRef.property }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.components.externalDns.releaseName }}
  namespace: {{ .Values.namespaces.platform }}
spec:
  interval: 10m0s
  releaseName: {{ .Values.components.externalDns.releaseName }}
  chart:
    spec:
      chart: {{ .Values.components.externalDns.chart.name }}
      version: {{ .Values.components.externalDns.chart.version | quote }}
      sourceRef:
        kind: {{ .Values.components.externalDns.sourceRef.kind }}
        name: {{ .Values.components.externalDns.sourceRef.name }}
        namespace: {{ .Values.components.externalDns.sourceRef.namespace }}
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    {{- toYaml .Values.components.externalDns.values | nindent 4 }}
{{- end }}
