{{- with .Values.components.postgresqlTlsIngress }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  namespace: {{ .namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .servicePort }}
      targetPort: {{ .servicePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .serviceName }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  ingressClassName: {{ .className }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ .secretName }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
{{- end }}
