{{- if .Values.agent.nodeExporter.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .Values.agent.nodeExporter.releaseName }}
  namespace: {{ .Values.namespaces.observability }}
spec:
  interval: 10m0s
  releaseName: {{ .Values.agent.nodeExporter.releaseName }}
  chart:
    spec:
      chart: {{ .Values.agent.nodeExporter.chart.name }}
      version: {{ .Values.agent.nodeExporter.chart.version | quote }}
      sourceRef:
        kind: {{ .Values.agent.nodeExporter.sourceRef.kind }}
        name: {{ .Values.agent.nodeExporter.sourceRef.name }}
        namespace: {{ .Values.agent.nodeExporter.sourceRef.namespace }}
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    {{- toYaml .Values.agent.nodeExporter.values | nindent 4 }}
{{- end }}
